### PR TITLE
Fix for Windows

### PR DESCRIPTION
**Pull request by OolaaPleur**

### CODE REVIEW

**Comment by rohitsangwan01** [comment]
@OolaaPleur Thank you for the PR!

Could you make only the minimal changes? This would make the review process easier. It seems like you’re just parsing the characteristic outside of uiThreadHandler and passing the resulting Char String instead of GattLocalChar.

Or am I missing something else?

**Comment by OolaaPleur** [comment]
Yeah, I guess. I never touched C++. Parsing it outside stopped it from localChar being null pointer on my PC (on laptop all works fine). This fixed my problem of crashing ble_peripheral and uni_control_hub. May be its not a good fix, at least I hope it will give some ideas, why on some hardwares app is crashing.

**Comment by rohitsangwan01** [comment]
@OolaaPleur i see, thats strange, are you sure localChar is null on your Pc ?

**Comment by OolaaPleur** [comment]
изображение

**Comment by rohitsangwan01** [comment]
Thankyou for the PR, closing in favour of https://github.com/rohitsangwan01/ble_peripheral/pull/21

**Pull request closed without merging**
